# Generated by Django 3.0.6 on 2020-05-24 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aifedayoscrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumygoals',
            options={'ordering': ('goal_status',)},
        ),
        migrations.AlterField(
            model_name='goalstatus',
            name='status_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_status', to='aifedayoscrumy.GoalStatus'),
        ),
    ]
