# Generated by Django 3.0.6 on 2020-05-28 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aifedayoscrumy', '0002_auto_20200524_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='goal_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aifedayoscrumy.GoalStatus'),
        ),
    ]
